---
  name: switch-release

  on:
    workflow_call:
      inputs:
        file-path:
            required: true
            type: string

  jobs:
    switch_release:
      runs-on: ubuntu-latest
      container: devkitpro/devkita64
      steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project
        run: make

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//} >> "$GITHUB_OUTPUT"

      - name: Rename
        id: rename
        run: |
          file_path=${{ inputs.file-path }}
          version=${{ steps.get_version.outputs.VERSION }}
          file_name=${fullfile##*/}
          file_ext=${fullfile##*.}
          final_file_path=${file_name}-${version}.${file_ext}
          mv ${file_path} ${final_file_path}
          echo "FINAL_FILE_PATH=${final_file_path}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: mikepenz/action-gh-release@v1
        with:
          files: ${{ steps.rename.outputs.FINAL_FILE_PATH }}
