---
  name: switch-release

  on:
    workflow_call:
      inputs:
        file-path:
            required: true
            type: string

  jobs:
    switch_release:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      container: devkitpro/devkita64
      steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project
        run: make

      - name: Rename
        id: rename
        run: |
          file_path=${{ inputs.file-path }}
          tag_name=${{ github.ref_name }}
          file_name=${file_path##*/}
          file_ext=${file_path##*.}
          final_file_path=${file_name}-${tag_name}.${file_ext}
          mv "${file_path}" "${final_file_path}"
          echo "final_file_path=${final_file_path}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: mikepenz/action-gh-release@v1
        with:
          files: ${{ steps.rename.outputs.final_file_path }}
